
#===== Makefile.config =======================================================80
#
#                              Record-Replay.Config
#
# author: 	Susanne van den Elsen
# date: 	2015
#
# Default settings should be overridden when non-default project setup is
# used.
#
#===============================================================================

#===== Variables =============================================================80
#
# Defined here:
#   	LLVMBASE      	: Path to the root directory of LLVM.
#   	LLVMBIN 
#	
#	CLANGBIN	: Path to the directory containing Clang binaries.
#	CLANG		: clang
#	CLANGXX		: clang++
#	CLANGPPFLAGS	: Clang preprocessor flags.	
#
#   	PASSSRC        : The LLVM directory for pass sources.
#   	PASSBUILD      : The LLVM directory for pass builds.
#   	PASSLIB        : The LLVM directory for pass dynamic libraries.
#   	PASSEXT        : The extension of dynamic libraries.
#
#   	UTILS          : The root directory of the subproject C++ Utils.
#  	BUILD          : The directory where Scheduler should be build.
#
#===============================================================================

LLVMBASE 	:= $(RECORD_REPLAY)/llvm
LLVMBIN		:= $(LLVMBASE)/build/Release+Debug+Asserts/bin

CLANGBIN	:= $(LLVMBIN)
CLANG		:= $(CLANG)
CLANGXX		:= $(CLANGBIN)/clang++
CLANGPPFLAGS	:= -I $(LLVMBASE)/build/include/c++/v1 

PASSSRC	 	:= $(LLVMBASE)/src/lib/Transforms
PASSBUILD	:= $(LLVMBASE)/build/lib/Transforms
PASSLIB		:= $(LLVMBASE)/build/Release+Debug+Asserts/lib/
PASSEXT 	:= dylib

UTILS       	?= ../cpp-utils
BUILD       	?= build
