
#===== Makefile.config =======================================================80
#
#                              Record-Replay.Config
#
# author: 	Susanne van den Elsen
# date: 	2015-2017
#
# Default settings should be overridden when non-default project setup is
# used.
#
#===============================================================================

#===== Variables =============================================================80
#
# Defined here:
#   	LLVMBASE      	: Path to the root directory of LLVM.
#   	LLVMBIN 
#	
#	CLANGBIN	: Path to the directory containing Clang binaries.
#	CLANG		: clang
#	CLANGXX		: clang++
#
#   	PASSEXT        : The extension of dynamic libraries.
#
#   	UTILS          : The root directory of the subproject C++ Utils.
#  	BUILD          : The directory where Scheduler should be build.
#
#===============================================================================

LLVMBASE	:= 
LLVMBIN		:= $(LLVMBASE)/build/bin

CLANGBIN	:= $(LLVMBIN)
CLANG		:= $(CLANGBIN)/clang
CLANGXX		:= $(CLANGBIN)/clang++

PASSEXT 	:= dylib

UTILS	        ?= 
BUILD       	?= build
